---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1fyj49j0ygjq4ux9wv67n85hk5lspgq4h4qcuzqr9sf2pm8ha0f0qtcdspn"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1fyj49j0ygjq4ux9wv67n85hk5lspgq4h4qcuzqr9sf2pm8ha0f0qtcdspn"
stores:
  yaml:
    indent: 2
