# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8PsJOmZoJeOlRQCoO5iI+GT3d9F1Qtisl5AMcFc9tS8=,iv:HlNpQ+aUXxPkdUWfIKstjHEmf3GawW+NzHJdzJ4iqx8=,tag:3fnFlYZCIqnsVtnMSPb7IQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fyj49j0ygjq4ux9wv67n85hk5lspgq4h4qcuzqr9sf2pm8ha0f0qtcdspn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZGpnS1MwOVhLeE5hU2J4
        bEJ2QXdpdkVDQlRjSE5pd2Y4L1JvWFVQNG0wCnJXVGN1K3RlcmFCQjE2TGZ0bkZS
        dEhucmkzc3ZzOHFoQUpHeWNBTGkvUEUKLS0tIE9jNWFDNzhLbmZFeWNpWnB1b3dK
        SnRRODBJb250a0RzeVJ0WjNENkVvdm8Kh3fXwuTOeCWhi2PBROhJHkTiX8Wp1Tjd
        IEiy6jMqPOEUHi0LldMPEq4oSwdIhLugfE1whPIcYRQHBeUveI3PLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-22T00:10:39Z"
  mac: ENC[AES256_GCM,data:+fzceqpNxfJbPjxVYP6VHVH1RHNjq3IfhfYIgV/qG+W6ooBKMFgjbOh5bIIVQNiNX2CufHAlPChI5ZeX21MTbY3HxgkhZcH10rk1i+H/vBHhYwfu+gBZtDgtAeu2mlfgXVJKdDQwD4T6nFb/MefVp2p5RH97mWtKmOqpD4lqoNI=,iv:PWCpGbxGHSw/0258uXfCuBU9TZSj6W2UEux3oymh2eo=,tag:6hsnDNWkjGnAyiHz61PShw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
