# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:NyPWnsMJsAKXibJbi/ro2hrsw42ry7ZBqWNG7lnPlcL8QQrd,iv:oDJOd48eHweFM+gZJIXSlzbqCgMfYGENothDmppwvgw=,tag:ZxwZ9GMv48XkAFJAE6qmiA==,type:str]
  credentials.json: ENC[AES256_GCM,data:bWKODdeIXn8BKzgaddCyW2NSBduWUF3P8O3yweCyreFeVzJXhKsvfq/tny5WKDEFRf3hz3IQj7o/DuAfPjeQ8ZE5N/ykvmfVXZWV/RTzwir4gPy1HuQADxgK36ITm8P6JPiy8Hd4Eu7n2wv5wZeExi31fZwhqM3F+iXN8qYyCfkDs2WAxutCMk8LZ4uRJt+9MQQqxEpV/HLhSf6t0FGLNqt559aDy+Wi6ZOUCIRSFg==,iv:2Ki8ZfqD0HPvAVYKiXAfKoT61FEewY5B3pyYmX/nFeE=,tag:hcuyIQPQewBnrCho1nYzVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fyj49j0ygjq4ux9wv67n85hk5lspgq4h4qcuzqr9sf2pm8ha0f0qtcdspn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ynl5WHNmOU9saTFJbkx4
        QVc0NHFHM2dlUEpvMFJPdWlwSXhwZ0huUzNnCktKL3A3cUlROGZKZXY5cGtzQytD
        UUZmRlVLTENFajkzVExlSGw4d2Q2UU0KLS0tIEI4VTJmbUdGNTFzSW4vVkpJWWow
        MW1NZzV5bnhMSmFid1hlTW9sTlE3MlUK4PIy6IZbJY3mqRUG+hEPhXaW0ElCgwkS
        DjGTKqQ+o+ul8bGeHxD7lsIwERMEPok9H1zH3X0VOAGzeGXFlLKVBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-22T00:10:39Z"
  mac: ENC[AES256_GCM,data:0RGKJFKuuX/VBSRuRf8Y+xdnnid5mITnt7/9E0HIJ+o4AKAR8yTQ5FgR8UJrTACZP/xLfvMrDuty6Yh4IKxZM2hJDZYRROmXHRI/qAlVhLyGtRBfwRLVYWeae91OM7fsh44gBNTbl3jQyfarpjDpFQI7+h9qMO5mh2SvIN4vE5M=,iv:oLIiWMesUFBaSkloOvnjKhYRt6ixfOmyhfc6fgayE1s=,tag:up/50/Qln/R/w7dlhIo5ZA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
