# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:c5KOPZbjUbtn6/6GC5tUx3U1JAt/yFoIsALnXWNYa/rrS+eVS+nAbA==,iv:Ca1wJ85PGLbGqVdMFT87GxY1xEbKSDDc61iBu5hwlZY=,tag:KiFHc43//9XI34qCa70wFw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fyj49j0ygjq4ux9wv67n85hk5lspgq4h4qcuzqr9sf2pm8ha0f0qtcdspn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZjJOQ2Uyb0IxOWFtM3Rm
        bmxsS29lTitORTFJSXorRVBGRGxMdlhSdDNFCnRVY3FUVTZxMmtsUHhsRzNzQ2My
        T3Z0cHhteUJZN2ZremxUY3p1Z3dYZmMKLS0tIGVHSUZyeFpGNklsMGdTZ2lKMmtJ
        Qlk5cS9lT1h0L1NBaEFreGcrUmQvMm8KUK4cK/K/ecq7T8DJ8rloAda9A710lJKd
        9T8dxPqGQaK7RbETRAHt5CQ9aDt02c+sBDLIfHWfanXMlPzN3ybh0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T23:47:05Z"
  mac: ENC[AES256_GCM,data:O7eVxZ0z+OLjilMmpJMIud8N5OqSGegpz0aoelJg8Pu4WSCMAPq13UyDVKIrWvX6zujdz0uu3lwjQtkFH70EpUPAD6ue4sQXYcMa4CKSMQPng7n0rKmfjVhdjTmEjmE80lfzmz9b2M70QuQeI1wPEn+iDJx6wkWY14R3RXOPnBg=,iv:XBiMwHqi7USnLsPF0UvaxGePbHB3HfBbOH3tnDfdE8o=,tag:XFNbxLHE2pcq6vXlrgo5Rw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
