---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pixelfed
spec:
  interval: 30m
  chart:
    spec:
      chart: pixelfed
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: pixelfed
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      tag: dev-nginx
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: pixelfed.talos.social
          paths:
            - path: /
              pathType: ImplementationSpecific
    autoscaling:
      enabled: true
    pixelfed:
      timezone: "America/Los_Angeles"
      app:
        existingSecret: pixelfed-secrets
        existingSecretKey: SECRET_PIXELFED_KEY
        name: "Pixelfed - talos.social"
        url: "https://pixelfed.talos.social"
        domain: "pixelfed.talos.social"
      instance:
        public_discover: true
      stories_enabled: true
      mail:
        from_address: pixelfed@talos.social
        existingSecret: pixelfed-secrets
        existingSecretKeys:
          host: SECRET_MAIL_SERVER
          port: SECRET_MAIL_PORT
          username: SECRET_MAIL_USERNAME
          password: SECRET_MAIL_PASSWORD
    postgresql:
      enabled: true
      global:
        storageClass: openebs-hostpath
    activity_pub:
      enabled: true
      remote_follow: true
    persistence:
      enabled: true
      storageClassName: openebs-hostpath
      storage: 100Gi
