# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-secrets
stringData:
  SECRET_PIXELFED_KEY: ENC[AES256_GCM,data:4aZnLVaNbh2KJGka3AF0T1OqQijPmWGWy4EuEoClZiyH56/4PqdSJGg7OUSLZtkNyt/HyLCL7eurC/TvvmhsJw==,iv:aeasB7J9xfgy0W7j6Mx4pG7XhLlvNFxXgYtb/O7eiVI=,tag:AAen8HCrShJwY+kca0iDaw==,type:str]
  SECRET_MAIL_SERVER: ENC[AES256_GCM,data:Or7U7peVbE/NjWU6dECnoxY=,iv:Kc1Hj8JSl8fZwvRjgL8qwTMx+Tb3+O+cm6Coi5FwHSA=,tag:Jkhp+aRjeqWZZMTbBzVgXg==,type:str]
  SECRET_MAIL_USERNAME: ENC[AES256_GCM,data:FK2E7pI8,iv:cQaCfrE3sDKVIvkgckMu9supqnXxj5MqUr2ejXP1FYk=,tag:P2NF10JdMGlUBj7hp7dTAQ==,type:str]
  SECRET_MAIL_PASSWORD: ENC[AES256_GCM,data:aJVb/OlDqxYjF6e7lNIJOgE6x7OrgkvbcmjDQVCDwSIoqXc0Blx2ZLfBci4C3bI29oc/CUUck76A5HZV8aaKII5Ptrbm,iv:V/qzo5bIJ+RsaEXVCPpvbwFSyjwUIuy0pb+pRQ/g6Gc=,tag:M/SFC6KecMvmZpijr74L6Q==,type:str]
  SECRET_MAIL_PORT: ENC[AES256_GCM,data:6LCo,iv:7meYpUNLExyb/tKybfgwYVEzBmWpHMN6v5FzBlxNhGM=,tag:oowe0PshoV2WiA+yHkrFSw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fyj49j0ygjq4ux9wv67n85hk5lspgq4h4qcuzqr9sf2pm8ha0f0qtcdspn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseWprWXV2cHVHYXN0YmRo
        eWNwZFJHWHhGcXNiWlBDbTArOVE5eUFobTNRCkVQZWxxQkwzZnZiR3dRa1AxVVNG
        MVpKdjl6N0U0ZWZlbHR4anZLMW1rdWMKLS0tIDhCUzhkanRVQ1I3MjVxNWhHMkNC
        M3pTS1FaeFRjWTdWNDdsT1h4N21pTGsK+o2rFO78dGQi6BuFUKqKwevRRHnhouQ6
        2Bq0Km7RSIjVFP9fZFZdJCNs1aQrkN0wBrylSWpArCmT1ufxsPeaVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-22T22:29:12Z"
  mac: ENC[AES256_GCM,data:vY26mPGa9qVYKiHQwH3pU6y41MZs/tUYu+gEu33F2mVsIfWf0jzkZX/1bnk8TWizZ2POTvT7n6dgZSYkIayukSJe9HJBxTeSPGWr1pjptKBPFF8w/2cz5KT17ZGN8LeJtKDYnKTg6gBp1dkOGvGzqWUq4X1SjJsmM8JGPnKdVPY=,iv:r4ucpbzcmwkD9ZhWPXUCqOMfh7wF85MYFi1jdgmSf88=,tag:gpezTwvmv1GuGCnRK/laiQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
